// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:shared/shared.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return Constants.shared().flavor == Flavor.dev ? androidDev : android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvh4rMEE_G2j2oehOCYT8B1ixKMC8TxD4',
    appId: '1:604495632390:android:d8ff1e7d8e483eb1e58b87',
    messagingSenderId: '604495632390',
    projectId: 'act-terralogic',
    storageBucket: 'act-terralogic.appspot.com',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAvh4rMEE_G2j2oehOCYT8B1ixKMC8TxD4',
    appId: '1:604495632390:android:2bb1054d8a8abb02e58b87',
    messagingSenderId: '604495632390',
    projectId: 'act-terralogic',
    storageBucket: 'act-terralogic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJbDxujWBBnu4GnHcFlVmNT_KC8R4izw',
    appId: '1:604495632390:ios:2e6cd55946ae545de58b87',
    messagingSenderId: '604495632390',
    projectId: 'act-terralogic',
    storageBucket: 'act-terralogic.appspot.com',
    iosClientId: '604495632390-hlvrku61evgru7bfclaofvbqescrku6k.apps.googleusercontent.com',
    iosBundleId: 'com.act.mobile.apps',
  );
}
